import os
import torch
import ujson
from torch import nn
from torch.utils.data import DataLoader, Dataset, random_split
from transformers import BertTokenizer, BertModel, AdamW, BertForSequenceClassification, AutoModelForCausalLM, AutoTokenizer
from sklearn.metrics import accuracy_score, classification_report
from tqdm import tqdm
import random
import numpy as np
import torch
from modelscope import snapshot_download
import re
from typing import List
from utils import pooling
os.environ["TOKENIZERS_PARALLELISM"] = "true"

os.environ["CUDA_VISIBLE_DEVICES"] = "2"
# os.environ['CUDA_VISIBLE_DEVICES'] = '2'


class BaseInference:
    def __init__(self, config, model, tokenizer, sample_param):
        self.config = config
        self.model = model
        self.tokenizer = tokenizer
        self.sample_param = sample_param
        self.system_prompt = ()
        self.system_prompt_refiner = ()
        self.system_prompt_multiple_choice = ()
        self.user_prompt_multiple_choice = ()
        self.user_prompt = ()
        self.system_prompt_naiverag = ()
        self.system_prompt_naiverag_multiple_choice = ()
        self.hlcn_examples = {
            'factual incorrectness': "Factual incorrectness occurs when the information provided by LLMs contains inaccuracies that contradict the meaning or intent of the query, but it can be drawn from the referenced documents. This includes misinterpretations or confusions involving nouns, actions, times, or places from the documents, leading to answers that are factually wrong relative to the query but still based on the provided content. For example, an LLM might incorrectly state a patient's blood sugar level as 150 mg/dL when the referenced documents say 120 mg/dL.",
            'logical error': "LLM may make logical errors in the final answer or the reasons for the answer, such as the reason contents is not logical, and there is no fixed truth value, or the logical reasoning relationship in the reason contradicts the logical relationship in the reference document. For example, a reference document might state that \"Artificial intelligence has developed rapidly in the field of deep learning in recent years. At the same time, quantum computing is attracting more and more research attention\", but LLMs can incorrectly generate the answer \"Due to the rapid development of deep learning, quantum computing is attracting more and more research attention\".",
            'question-answer inconsisitency': "The answers generated by LLMs may not be consistent with the query intent of the question, that is, the answers may not address the requirements of the question, or the answers may not satisfy the constraints of the question. For example, the question may be \"Please list the fruits that may be sold in the supermarket\", but the LLM may answer \"Apples, bananas, cabbage, beef\"",
            'fabrication': "LLM creates the answer that is either unfaithful or unverifiable using the given documents (even when it is factually correct). For example, a LLM may use a famous quote, but the quote never appears in the referenced documents."
        }
        self.system_prompt_format_checker = ()
        self.user_prompt_format_checker = ()
    
    def make_prompts(self, *args, **kwargs):
        pass
    
    def make_prompt_check_format(self, *args):
        pass
        
    def make_prompts_multiple_choice(self, *args):
        pass
    
    def make_prompts_wrong(self, *args):
        pass
    
    def format_reference(self, retrieval_result):
        format_reference = ""
        for idx, doc_item in enumerate(retrieval_result):
            # if isinstance(doc_item, list):
            #     print(retrieval_result)
            #     print(doc_item)
            content = doc_item["contents"]
            title = content.split("\n")[0]
            text = "\n".join(content.split("\n")[1:])
            # if format_reference is not None:
            #     format_reference += format_reference.format(idx=idx, title=title, text=text)
            # else:
            #     format_reference += f"Doc {idx+1}(Title: {title}) {text}\n"
            # if format_reference is None:
            #     format_reference += f"Doc {idx+1}(Title: {title}) {text}\n"
            text = re.sub(r'[\{\}]', '', text)
            format_reference += f"Doc {idx+1}(Title: {title}) {text}\n"

        return format_reference
    
    def format_options(self, options):
        format_options = ""
        for idx, option in enumerate(options):
            format_options += f"[{idx+1}] {option}\n"
        return format_options
    
    def format_judgments(self, judgments):
        format_judgments = ""
        for idx, judgment in enumerate(judgments):
            format_judgments += f"Judgment {idx+1}: {judgment}\n"
        return format_judgments 
    
    def inference(self, *args, rag_type='LLM ensemble', hlcn_type="", check_format=False, multiple_choice=False, wrong_answer=False):
        # print(self.__class__.__name__)
        if not wrong_answer:
            if not multiple_choice:
                if first_turn:
                    system_prompt, user_prompt = self.make_prompts(*args)
                else:
                    system_prompt, user_prompt = self.make_prompts_rethink(*args)
            else:
                if first_turn:
                    system_prompt, user_prompt = self.make_prompts_multiple_choice(*args)
                else:
                    system_prompt, user_prompt = self.make_prompts_rethink_multiple_choice(*args)
                if rag_type == 'naive':
                    system_prompt = [self.system_prompt_naiverag_multiple_choice] * len(user_prompt)
            if rag_type == 'naive':
                system_prompt, user_prompt = self.make_prompts_naiverag(*args)
        
        if isinstance(self, Generator) and wrong_answer:
            system_prompt, user_prompt = self.make_prompts_wrong(*args)
        text = [
            self.tokenizer.apply_chat_template(
            [
                {'role': 'system', 'content': system_prompt_},
                {'role': 'user', 'content': user_prompt_}
            ],
            tokenize=False,
            add_generation_prompt=True
        ) for system_prompt_, user_prompt_ in zip(system_prompt, user_prompt)
        ]
        
        output = self.model.generate(
            text,
            self.sample_param,
            use_tqdm=False,
        )
        response = [output_.outputs[0].text for output_ in output]
        print(response)
        return response
   
class ExtractiveRefiner(BaseInference):
    def __init__(self, config, model, tokenizer, sample_param):
        super().__init__(config, model, tokenizer, sample_param)
        self.topk = config["refiner_topk"]
        self.pooling_method = config["refiner_pooling_method"]
        self.encode_max_length = config["refiner_encode_max_length"]
        self.model, self.tokenizer, self.sample_param = model, tokenizer, sample_param
        
    def encode(self, query_list: List[str], is_query=True):
        if is_query:# 判断处理query还是处理documents
            query_list = [f"query: {query}" for query in query_list]
        else:
            query_list = [f"passage: {query}" for query in query_list]

        inputs = self.tokenizer(
            query_list, max_length=self.encode_max_length, padding=True, truncation=True, return_tensors="pt"
        )
        inputs = {k: v.cuda() for k, v in inputs.items()}

        if "T5" in type(self.model).__name__:
            # T5-based retrieval model
            decoder_input_ids = torch.zeros((inputs["input_ids"].shape[0], 1), dtype=torch.long).to(
                inputs["input_ids"].device
            )
            output = self.model(**inputs, decoder_input_ids=decoder_input_ids, return_dict=True)
            query_emb = output.last_hidden_state[:, 0, :]

        else:
            output = self.model(**inputs, return_dict=True)
            query_emb = pooling(
                output.pooler_output, output.last_hidden_state, inputs["attention_mask"], self.pooling_method
            )

        query_emb = query_emb.detach().cpu().numpy()
        query_emb = query_emb.astype(np.float32)
        return query_emb

    def batch_run(self, questions, retrieval_results, batch_size=16):
        # only use text
        retrieval_results = [
            ["\n".join(doc_item["contents"].split("\n")[1:]) for doc_item in item_result]
            for item_result in retrieval_results
        ]

        # split into sentences: [[sent1, sent2,...], [...]]
        # print(retrieval_results)
        # sent_lists = [
        #     [i.strip() for i in re.split(r"(?<=[.!?])\s+", res) if len(i.strip()) > 5] for res in retrieval_results
        # ]
        sent_lists = retrieval_results
        score_lists = []  # matching scores, size == sent_lists
        for idx in tqdm(range(0, len(questions), batch_size), desc="Refining process: "):
            batch_questions = questions[idx : idx + batch_size]
            batch_sents = sent_lists[idx : idx + batch_size]

            question_embs = self.encode(batch_questions, is_query=True)
            sent_embs = self.encode(sum(batch_sents, []), is_query=False)  # n*d
            scores = question_embs @ sent_embs.T
            start_idx = 0
            for row_score, single_list in zip(scores, sent_lists):
                row_score = row_score.tolist()
                score_lists.append(row_score[start_idx : start_idx + len(single_list)])
                start_idx += len(single_list)

        # select topk sents
        retain_lists = []
        for sent_scores, sent_list in zip(score_lists, sent_lists):
            if len(sent_scores) < self.topk:
                retain_lists.append(sent_list)
                continue
            topk_idxs = torch.topk(torch.Tensor(sent_scores), self.topk).indices.tolist()
            retain_lists.append([sent_list[idx] for idx in sorted(topk_idxs)])

        return [" ".join(sents) for sents in retain_lists]
    
class AbstractiveRecompRefiner(BaseInference):
    def __init__(self, config, model, tokenizer, sample_param):
        super().__init__(config, model, tokenizer, sample_param)
        self.max_input_length = config["refiner_max_input_length"]
        self.max_output_length = config["refiner_max_output_length"]
        self.model, self.tokenizer, self.sample_param = model, tokenizer, sample_param
        
    def batch_run(self, questions, retrieval_results, batch_size=2):
        # only use text
        retrieval_results = [
            ["\n".join(doc_item["contents"].split("\n")[1:]) for doc_item in item_result]
            for item_result in retrieval_results
        ]

        # input processing in recomp training format
        format_inputs = [
            "Question: {question}\n Document: {document}\n Summary: ".format(
                question=question, document="\n".join(docs)
            )
            for question, docs in zip(questions, retrieval_results)
        ]

        results = []
        for idx in tqdm(range(0, len(format_inputs), batch_size), desc="Refining process: "):
            batch_texts = format_inputs[idx : idx + batch_size]
            outputs = self.model.generate(
                batch_texts,
                self.sample_param
            )
            batch_outputs = [output.outputs[0].text for output in outputs]

            results.extend(batch_outputs)

        return results
    
class Generator(BaseInference):
    def __init__(self, config=None, model=None, tokenizer=None, sample_param=None):
        super().__init__(config, model, tokenizer, sample_param)
        self.system_prompt = (
            # "Given a question and referenced documents, generate an entirely incorrect answer (e.g., a wrong noun or concept) "
            # "that contradicts the correct one, but is still grounded by some of the information in the documents. Follow these steps:\n"
            # "1. Carefully read the referenced documents and understand the query intent.\n"
            # "2. Generate a factually incorrect answer by creating a different, incorrect noun or concept, but not merely negating the correct answer.\n"
            # "3. Only generate the incorrect answer, and do not provide any reasons for the answer.\n"
            # "4. Do not imply that the answer is incorrect, and do not mention any information about the real correct answer.\n"
            # "Keep in mind: \n1. Do not provide correct answers or point out that the answer is wrong.\n"
            # "2. Ensure consistency with the documents while generating the incorrect answer.\n\n"
            # "Example:\n"
            # "Question: Which animal is the fastest on land?\n"
            # "Referenced Documents: <a story about The Tortoise and the Hare>\n\n"
            # "Answer: The turtle is the fastest animal on land. "
            
            "Given a question and referenced documents, generate an entirely incorrect answer (e.g., a wrong noun or concept) "
            "that contradicts the correct one, but is still grounded by some of the information in the documents. "
            "Follow these steps:\n1. Generate a factually incorrect answer by creating a different, incorrect noun or concept, "
            "but not merely negating the correct answer.\n2. Only generate the incorrect answer, and do not provide any reasons for the answer.\n"
            "3. Do not imply that the answer is incorrect, and do not mention any information about the real correct answer.\n"
            "Keep in mind: \n1. Do not provide correct answers or point out that the answer is wrong.\n"
            "2. Ensure consistency with the documents while generating the incorrect answer.\n\n"
            "Example:\nQuestion: Which animal is the fastest on land?\nReferenced Documents: <a story about The Tortoise and the Hare>\n\n"
            "Answer: The turtle is the fastest animal on land. "
            
            # "Here is a question and some referenced documents. "
            # "You are now asked to read the referenced documents carefully, and then answer the question based only on the contents of the given documents, and do not base it on your own internal knowledge but based only on the contents of the given documents. "
            # "Only give me the answer and do not output any other words."
        )
        self.system_prompt_multiple_choice = (
            "Given a multiple-choice question, some referenced documents and some available options. "
            "Your task is to select an incorrect option that contradicts the question's intended meaning, but is still justifiable based on the documents. "
            "When generating your option, follow these steps:\n"
            "1. Identify relevant information from the documents.\n"
            "2. Select a factually incorrect option that opposes the correct interpretation.\n"
            "3. Briefly justify the incorrect choice using evidence from the documents, making it seem plausible.\n\n"
            "Do not provide the correct option or state that the option is wrong. Ensure the explanation aligns with the document while supporting the wrong choice.\n\n"
            "Here is an example:\n"
            "Question: Which animal is the fastest on land?\n"
            "Available Options: \n[1] Butterfly\n[2] Turtle\n[3] Snake\n[4] Lizard\n\n"
            "Option and Reasons: [2]. Document A notes that turtles are agile in specific situations, such as evading predators. "
            "Document B suggests their slow movement aids survival, which could be interpreted as metaphorical speed."
        )
        self.user_prompt = (
            "Question: {question}\n\n"
            "Referenced Documents: \n{documents}"
        )
        self.user_prompt_multiple_choice = (
            "Question: {question}\n\n"
            "Referenced Documents: \n{documents}\n\n"
            "Available Options: \n{options}"
        )
        self.system_prompt_naiverag = (
            "Here is a question and some referenced documents. "
            "You are now asked to read the referenced documents carefully, and then answer the question based only on the contents of the given documents, and do not base it on your own internal knowledge but based only on the contents of the given documents. "
            "Only give me the answer and do not output any other words."
        )
        self.system_prompt_naiverag_multiple_choice = (
            "Given a multiple-choice question, some referenced documents and some available options. "
            "You are now asked to read the referenced documents carefully, and then select a correct option to answer the question based only on the contents of the given documents, "
            "and do not base it on your own internal knowledge but based only on the contents of the given documents. "
            "Only give me the index of the correct option and do not output any other words.\n\n"
            "Here is an example:\n"
            "Question: Which animal is the fastest on land?\n"
            "Available Options: \n[1] Butterfly\n[2] Turtle\n[3] Snake\n[4] Cheetah\n\n"
            "Your Option: [4]"
        )
        
    def make_prompts(self, question, retrieval_results):
        format_references = [self.format_reference(retrieval_result) for retrieval_result in retrieval_results]
                
        input_params = [{'question': question_, 'documents': format_reference} for question_, format_reference in zip(question, format_references)]
        return [self.user_prompt.format(**input_param) for input_param in input_params]
    
    def make_prompts_multiple_choice(self, question, retrieval_results, options):
        format_references = [self.format_reference(retrieval_result) for retrieval_result in retrieval_results]
        
        format_options = [self.format_options(options_) for options_ in options]
        input_params = [{'question': question_, 'documents': format_reference, 'options': format_options_} for question_, format_reference, format_options_ in zip(question, format_references, format_options)]
        return [self.user_prompt_multiple_choice.format(**input_param) for input_param in input_params]
    
class Checker(BaseInference):
    def __init__(self, config=None, model=None, tokenizer=None, sample_param=None):
        super().__init__(config, model, tokenizer, sample_param)
        self.hlcn_type = ""
        self.system_prompt = (
            "Given a question, some referenced documents, and an answer for the question according to the contents of referenced documents generated by a LLM, "
            "review the documents carefully, and determine whether the answer given exhibits a \"{hlcn_type}\" problem with the contents of referenced documents"
            "(that is, {example}). If so, output \"The answer has \"{hlcn_type}\" problem.\" in the first line. Follow this with reasons for your judgment, "
            "refuting the original answer and presenting the correct answer, based on the contents of the documents. "
            "If not, only output \"The answer and reasons do not have \"{hlcn_type}\" problem.\", and do not output anything else. "
            "Keep in mind: \n1. Focus only on essential details, and summarize and refine your judgment.\n"
            "2. Strictly follow this format without adding any extra information.",
        )
        self.system_prompt_format_checker = (
            # 经过ChatGPT修改过
            "Given a question and its answer, simplify the answer by removing redundant phrases while strictly retaining all key details "
            "(e.g., names, times, places, or numbers). Follow these steps:\n1. For yes\/no questions, "
            "the simplified answer should only be either 'yes' or 'no.'\n2. For open-ended or fact-based questions, "
            "only retain key nouns (e.g., names, places, times, or numbers) without altering any factual information, "
            "and remove any unnecessary details or unnecessary phrases.\n3. If the answer is already concise and correct, "
            "only output a 'No need change.'\n\nEnsure that:\n1. The simplified answer should contain only key nouns or numbers, "
            "but not a complete sentence with subject-verb objects.\n2. Retain proper names and titles in their full form "
            "(e.g., 'Street,' 'Avenue,' 'Company').\n3. Do not change the key nouns or factual details(e.g., numbers, dates, proper names). \n"
            "4. If the answer already meets these criteria, only respond with a 'No need change.', avoid further simplification the answer.\n\n",
        )
        self.system_prompt_multiple_choice = (
            "Here is a multiple-choice question and some referenced documents, along with an option selected from the provided options "
            "according to the contents of the referenced documents, generated by a LLM. "
            "You are now asked to review the documents carefully, and determine whether the selected option exhibits a \"{hlcn_type}\" problem "
            "with the contents of the referenced documents (that is, {example}). "
            "Follow this with reasons for your judgment, refuting the original selection and presenting the correct option, based on the contents of the documents. "
            "If not, only output \"The answer and reasons do not have \"{hlcn_type}\" problem.\", and do not output anything else. "
            "Please adhere strictly to this output format and refrain from including any additional information."
        )
        # 对于multiple choice，不需要简化步骤
        self.user_prompt = (
            "Question: {question}\n\n"
            "Referenced Documents: \n{documents}\n\n"
            "Answer: {answer}"
        )
        self.user_prompt_multiple_choice = (
            "Question: {question}\n\n"
            "Referenced Documents: \n{documents}\n\n"
            "Available Options: \n{options}\n\n"
            "LLM's Option: {option}"
        )
        self.user_prompt_format_checker = (
            "Question: {question}\n"
            "Answer to be modified: {answer}\n"
            "Modified Answer: "
        )
        
    def make_prompts(self, question, retrieval_results, answer):
        format_references = [self.format_reference(retrieval_result) for retrieval_result in retrieval_results]
        
        input_params = [{'question': question_, 'documents': format_reference, 'answer': answer_} for question_, format_reference, answer_ in zip(question, format_references, answer)]
        return [self.user_prompt.format(**input_param) for input_param in input_params]
    
    def make_prompts_multiple_choice(self, question, retrieval_results, options, option):
        format_references = [self.format_reference(retrieval_result) for retrieval_result in retrieval_results]
        format_options = [self.format_options(options_) for options_ in options]
        input_params = [{'question': question_, 'documents': format_reference, 'options': format_options_, 'option': option_} for question_, format_reference, format_options_, option_ in zip(question, format_references, format_options, option)]
        return [self.user_prompt_multiple_choice.format(**input_param) for input_param in input_params]
    
    def make_prompt_check_format(self, question, answer):
        input_params = [{'question': question_, 'answer': answer_} for question_, answer_ in zip(question, answer)]
        return [self.user_prompt_format_checker.format(**input_param) for input_param in input_params]
    
class Modifier(BaseInference):
    def __init__(self, config=None, model=None, tokenizer=None, sample_param=None):
        super().__init__(config, model, tokenizer, sample_param)
        self.system_prompt = (
            "Given a question, some referenced documents, an answer generated by a LLM to answer the question and several LLM's judgments "
            "for the answer's hallucination problems, follow these steps:\n1. Identify the query intent of the question and "
            "determine what type of correct answer should be (e.g., a name, a time, a place, etc.).\n2. Review the question's "
            "intent and documents and the judgment carefully. \n3. Revise the answer according to the question, the documents and judgment, "
            "and output a final correct answer. \n4. The answer should be strictly based on the documents and the judgment. "
            "Can not create an answer that does not exist in the documents.\n5. Only output the final modified answer, "
            "and do not output any other words, do not output any judgement or explanation. \n\nNote that: "
            "The correct answer should fit the query intent (e.g., if the question asks for a time, do not output a place, a person, etc).",
        )
        
        self.user_prompt = (
            "Question: {question}\n\n"
            "Referenced Documents: \n{documents}\n\n"
            "Answer: {answer}\n\n"
            "Judgments: \n{judgments}"
        )
        self.system_prompt_multiple_choice = (
            "Given a question, some referenced documents, some available options, an option chosen by a LLM to answer "
            "the question, and several LLM's judgments to determine whether the option has problems and types of problems. "
            "Review the provided question, referenced documents, available options, and the LLM's option. "
            "Based on the judgments of several LLMs regarding any issues with the option, "
            "synthesize this information to choose a final correct option. "
            "Keep in mind: \n1. The correct information must be found in the referenced documents. \n"
            "2. Ensure the option you choose directly addresses the question's intent. \n"
            "3. Analyze the contents of the documents and the LLM judgments thoroughly, ensuring no information is overlooked. \n"
            "4. Only provide the index number of the correct option in the format [n], where n is the index of the correct option (e.g., [1], [2], etc.), and no other text.\n"
            "5. Provide only your final option, without explanations or repetition of the question. Avoid phrases like 'No information'. "
            "6. It is guaranteed that one of the provided options is the correct answer."
        )
        self.user_prompt_multiple_choice = (
            "Question: {question}\n\n"
            "Referenced Documents: \n{documents}\n\n"
            "Available Options: \n{options}\n\n"
            "LLM's Option: {option}\n"
            "Judgments: \n{judgments}"
        ) 
        
    def make_prompts(self, question, retrieval_results, answer, judgments):
        format_judgments = [self.format_judgments(judgment) for judgment in judgments]
        format_references = [self.format_reference(retrieval_result) for retrieval_result in retrieval_results]
        input_params = [{'question': question_, 'documents': format_reference, 'answer': answer_, 'judgments': format_judgment} for question_, format_reference, answer_, format_judgment in zip(question, format_references, answer, format_judgments)]
        return [self.user_prompt.format(**input_param) for input_param in input_params]
    
    def make_prompts_multiple_choice(self, question, retrieval_results, options, option, judgments):
        format_judgments = [self.format_judgments(judgment) for judgment in judgments]
        format_references = [self.format_reference(retrieval_result) for retrieval_result in retrieval_results]
        format_options = [self.format_options(options_) for options_ in options]
        input_params = [{'question': question_, 'documents': format_reference, 'options': format_options_, 'option': option_, 'judgments': format_judgment} for question_, format_reference, format_options_, option_, format_judgment in zip(question, format_references, format_options, option, format_judgments)]
        return [self.user_prompt_multiple_choice.format(**input_param) for input_param in input_params]
    
class Rethinker(BaseInference):
    def __init__(self, config=None, model=None, tokenizer=None, sample_param=None):
        super().__init__(config, model, tokenizer, sample_param)
        self.system_prompt = (
            "Given a question, referenced documents, and an answer generated by a LLM, along with a \"{hlcn_type}\" problem judgment generated by a LLM "
            "(that is, {example})and answers for LLM's judgment, Follow these steps:\n1. Review the question, the documents and the judgment carefully. \n"
            "2. Check whether the judgment about the correctness of the answer is reasonable and is consistent with the documents. \n"
            "3. If the judgment correctly determines the answer, only output a 'The judgment is correct', and nothing else. \n"
            "4. If the judgment is incorrect:\n(1) First, output: 'The judgment is incorrect'.\n"
            "(2) Then generate a new judgment based on the contents of the documents to determine the correctness of the answer. \n"
            "Keep in mind:\nIf a new judgment is needed:\n1. It must address the original judgment's mistakes and be more accurate.\n"
            "2. It should focus on whether the answer matches the query intent and document consistency, not just replicating the original judgment. \n"
            # "5. There must be the correct answer in the reference documents, so carefully analyze the contents of the documents and do not miss information."
        )
        self.system_prompt_multiple_choice = (
            "Given a question, some referenced documents, some available options, an option chosen by a LLM to answer "
            "the question, and a judgment generated by a LLM to determine if the option has a \"{hlcn_type}\" problem"
            "(that is, {example})and answers for LLM's judgment. "
            "Your task is to assess the judgment based on the documents:\n"
            "1. Analyze the documents to assess the accuracy of the judgment. \n"
            "2. Determine if the judgment should be optimized for accuracy, reversed, or left unchanged. \n\n"
            "Guidelines are as follows:\n"
            "1. Avoid unnecessary details or lengthy explanations.\n"
            "2. If no change is needed, only respond with a \"No revise is required.\". \n"
            "3. If a revision is needed, provide only the revised judgment, without additional explanations. "
            "Ensure your analysis is concise and based solely on the information in the documents."
        )
        self.user_prompt = (
            "Question: {question}\n\n"
            "Referenced Documents: \n{documents}\n\n"
            "Answer: {answer}\n\n"
            "Judgment: \n{judgments}"
        )
        self.user_prompt_multiple_choice = (
            "Question: {question}\n\n"
            "Referenced Documents: \n{documents}\n\n"
            "Available Options: \n{options}\n\n"
            "LLM's Option: {option}\n"
            "Judgment: \n{judgments}"
        )
        
    def make_prompts(self, question, retrieval_results, answer, judgments):
        # format_judgments = [self.format_judgments(judgment) for judgment in judgments]
        format_references = [self.format_reference(retrieval_result) for retrieval_result in retrieval_results]
        input_params = [
                {'question': question_, 'documents': format_reference, 'answer': answer_, 'judgments': judgment} 
                for question_, format_reference, answer_, judgment in zip(question, format_references, answer, judgments)
            ]
        return [self.user_prompt.format(**input_param) for input_param in input_params]
        
    def make_prompts_multiple_choice(self, question, retrieval_results, options, option, judgments):
        format_judgments = [self.format_judgments(judgment) for judgment in judgments]
        format_references = [self.format_reference(retrieval_result) for retrieval_result in retrieval_results]
        format_options = [self.format_options(options_) for options_ in options]
        input_params = [{'question': question_, 'documents': format_reference, 'options': format_options_, 'option': option_, 'judgments': format_judgment} for question_, format_reference, format_options_, option_, format_judgment in zip(question, format_references, format_options, option, format_judgments)]
        return [self.user_prompt_multiple_choice.format(**input_param) for input_param in input_params]